export const supportedLanguages = { // eslint-disable-line
  afrikaans: { 
    transliteration: false, 
    localName: null, 
    totalSpeakers: '7,200,000',
    family: ['Indo-European', 'Germanic', 'West Germanic', 'Low Franconian', 'Dutch'],
    spokenIn: ['South Africa', 'Namibia'],
  },
  arabic: { 
    transliteration: true, 
    localName: 'عَرَبِيّ‎',
    totalSpeakers: '310,000,000',
    family: ['Afro-Asiatic', 'Semitic', 'West Semitic', 'Central Semitic'],
    spokenIn: ['Egypt', 'Algeria', 'Sudan', 'Saudi Arabia', 'Morocco', 'Iraq', 'Syria', 'Yemen', 'Tunisia', 'Jordan', 'Libya', 'Lebanon', 'Somalia', 'United Arab Emirates', 'Mauritania', 'Oman', 'Israel', 'Kuwait', 'Palestine', 'Chad', 'Qatar', 'Bahrain', 'Eritrea', 'Djibouti'], 
  },
  mandarin: { 
    transliteration: true, 
    localName: '中文',
    totalSpeakers: '910,000,000',
    family: ['Sino-Tibetan', 'Sinitic'],
    spokenIn: ['China', 'Taiwan', 'Singapore'],
  },
  cantonese: { 
    transliteration: true, 
    localName: '廣州話',
    totalSpeakers: '80,000,000',
    family: ['Sino-Tibetan', 'Chinese', 'Yue', 'Yuehai'],
    spokenIn: ['China', 'Hong Kong', 'Macao'],
  },
  czech: { 
    transliteration: false, 
    localName: 'čeština',
    totalSpeakers: '10,700,000',
    family: ['Indo-European', 'Balto-Slavic', 'Slavic', 'West Slavic', 'Czech-Slovak'],
    spokenIn: ['Czech Republic'],
  },
  danish: { 
    transliteration: false, 
    localName: 'dansk',
    totalSpeakers: '5,500,000',
    family: ['Indo-European', 'Germanic', 'North Germanic', 'South Scandinavian'],
    spokenIn: ['Denmark'], 
  },
  dutch: { 
    transliteration: false, 
    localName: 'nederlands',
    totalSpeakers: '22,000,000',
    family: ['Indo-European', 'Germanic', 'West Germanic', 'Low Franconian'],
    spokenIn: ['Netherlands', 'Belgium', 'Suriname', 'Aruba', 'Curacao', 'Sint Maarten'], 
  },
  finnish: { 
    transliteration: false, 
    localName: 'suomi',
    totalSpeakers: '5,400,000',
    family: ['Uralic', 'Finnic'],
    spokenIn: ['Finland'],
  },
  french: { 
    transliteration: false, 
    localName: 'français',
    totalSpeakers: '76,000,000',
    family: ['Indo-European', 'Italic', 'Romance', 'Western Romance', 'Gallo-Romance'],
    spokenIn: ['Democratic Republic of Congo', 'France', 'Canada', 'Madagascar', 'Cameroon', 'Ivory Coast', 'Niger', 'Burkina Faso', 'Mali', 'Senegal', 'Chad', 'Guinea', 'Rwanda', 'Belgium', 'Burundi', 'Benin', 'Haiti', 'Switzerland', 'Togo', 'Central African Republic', 'Congo', 'Gabon', 'Equatorial Guinea', 'Djibouti', 'Comoros', 'Luxembourg', 'Vanuatu', 'Seychelles', 'Monaco'],
  },
  german: { 
    transliteration: false, 
    localName: 'deutsch',
    totalSpeakers: '90,000,000',
    family: ['Indo-European', 'Germanic', 'West Germanic', 'High German'],
    spokenIn: ['Germany', 'Austria', 'Switzerland', 'Belgium', 'Luxembourg', 'Liechtenstein'],
  },
  greek: { 
    transliteration: true, 
    localName: 'ελληνικά',
    totalSpeakers: '13,400,000',
    family: ['Indo-European', 'Hellenic'],
    spokenIn: ['Greece', 'Cyprus'],
  },
  hebrew: { 
    transliteration: true, 
    localName: 'עִבְרִית',
    totalSpeakers: '5,000,000',
    family: ['Afro-Asiatic', 'Semitic', 'Central Semitic', 'Northwest Semitic', 'Canaanite'],
    spokenIn: ['Israel'],
  },
  hindi: { 
    transliteration: true, 
    localName: 'हिन्दी',
    totalSpeakers: '322,000,000',
    family: ['Indo-European', 'Indo-Iranian', 'Indo-Aryan', 'Central Zone', 'Western Hindi', 'Hindustani', 'Khariboli'],
    spokenIn: ['India'],
  },
  hungarian: { 
    transliteration: false, 
    localName: 'magyar',
    totalSpeakers: '13,000,000',
    family: ['Uralic', 'Finno-Ugric', 'Ugric'],
    spokenIn: ['Hungary'],
  },
  italian: { 
    transliteration: false, 
    localName: 'italiano',
    totalSpeakers: '69,000,000',
    family: ['Indo-European', 'Italic', 'Romance', 'Italo-Western', 'Italo-Dalmation'],
    spokenIn: ['Italy', 'Switzerland', 'San Marino', 'Vatican City'],
  },
  japanese: { 
    transliteration: true, 
    localName: '日本語',
    totalSpeakers: '125,000,000',
    family: ['Japonic'],
    spokenIn: ['Japan'],
  },
  khmer: { 
    transliteration: true, 
    localName: 'ភាសាខ្មែរ',
    totalSpeakers: '16,000,000',
    family: ['Austroasiatic'],
    spokenIn: ['Cambodia'],
  },
  burmese: { 
    transliteration: true, 
    localName: 'မြန်မာဘာသာ',
    totalSpeakers: '33,000,000',
    family: ['Sino-Tibetan', 'Lolo-Burmese', 'Burmish'],
    spokenIn: ['Myanmar'],
  },
  korean: { 
    transliteration: true, 
    localName: '한국어',
    totalSpeakers: '77,200,000',
    family: ['Koreanic', 'Han', 'Sillan'],
    spokenIn: ['South Korea', 'North Korea', 'China'],
  },
  lao: { 
    transliteration: true, 
    localName: 'ລາວ',
    totalSpeakers: '3,000,000',
    family: ['Kra-Dai', 'Tai', 'Southwestern Tai', 'Lao-Phutai'],
    spokenIn: ['Laos'],
  },
  norwegian: { 
    transliteration: false, 
    localName: 'norsk',
    totalSpeakers: '5,200,000',
    family: ['Indo-European', 'Germanic', 'North Germanic'],
    spokenIn: ['Norway'],
  },
  polish: {
    transliteration: false, 
    localName: 'polski',
    totalSpeakers: '45,000,000',
    family: ['Indo-European', 'Balto-Slavic', 'Slavic', 'West Slavic', 'Lechitic'],
    spokenIn: ['Poland'],
  },
  portuguese: { 
    transliteration: false, 
    localName: 'português',
    totalSpeakers: '223,000,000',
    family: ['Indo-European', 'Italic', 'Romance', 'Western Romance', 'Ibero-Romance', 'West Iberian', 'Galician-Portuguese'],
    spokenIn: ['Brazil', 'Angola', 'Mozambique', 'Portugal', 'Guinea-Bissau', 'East Timor', 'Equatorial Guinea', 'Macao', 'Cape Verde', 'Sao Tome and Principe'],
  },
  russian: { 
    transliteration: true, 
    localName: 'русский',
    totalSpeakers: '150,000,000',
    family: ['Indo-European', 'Balto-Slavic', 'Slavic', 'East Slavic'],
    spokenIn: ['Russia', 'Kazakhstan', 'Belarus', 'Kyrgyzstan', 'Turkmenistan', 'Uzbekistan', 'Tajikistan', 'Moldova'],
  },
  spanish: { 
    transliteration: false, 
    localName: 'español',
    totalSpeakers: '480,000,000',
    family: ['Indo-European', 'Italic', 'Romance', 'Western Romance', 'Ibero-Romance', 'West Iberian', 'Castilian'],
    spokenIn: ['Mexico', 'Colombia', 'Spain', 'Argentina', 'Peru', 'Venezuela', 'Chile', 'Ecuador', 'Guatemala', 'Cuba', 'Bolivia', 'Dominican Republic', 'Honduras', 'Paraguay', 'El Salvador', 'Nicaragua', 'Costa Rica', 'Puerto Rico', 'Panama', 'Uruguay', 'Equatorial Guinea'],
  },
  swedish: {
    transliteration: false, 
    localName: 'svenska',
    totalSpeakers: '10,000,000',
    family: ['Indo-European', 'Germanic', 'North Germanic', 'North Scandinavian'],
    spokenIn: ['Sweden', 'Finland'],
  },
  thai: { 
    transliteration: true, 
    localName: 'ภาษาไทย',
    totalSpeakers: '36,000,000',
    family: ['Kra-Dai', 'Tai', 'Southwestern Tai', 'Chiang Saen'],
    spokenIn: ['Thailand'],
  },
  turkish: { 
    transliteration: false,
    localName: 'türkçe',
    totalSpeakers: '75,700,000',
    family: ['Turkic', 'Common Turkic', 'Oghuz', 'Western Oghuz'],
    spokenIn: ['Turkey', 'Cyprus'],
  },
  urdu: { 
    transliteration: true, 
    localName: 'اُردُو‎',
    totalSpeakers: '67,000,000',
    family: ['Indo-European', 'Indo-Iranian', 'Indo-Aryan', 'Central Zone', 'Western Hindi', 'Hindustani', 'Khariboli'],
    spokenIn: ['Pakistan', 'India', 'Nepal'],
  },
  vietnamese: { 
    transliteration: false, 
    localName: 'tiếng việt',
    totalSpeakers: '96,000,000',
    family: ['Austroasiatic', 'Vietic', 'Viet-Muong'],
    spokenIn: ['Vietnam'],
  },
  bengali: {
    transliteration: true,
    localName: 'বাংলা',
    totalSpeakers: '261,000,000',
    family: ['Indo-European', 'Indo-Iranian', 'Indo-Aryan', 'Magadhi Prakrit', 'Eastern Zone', 'Bengali-Assamese'],
    spokenIn: ['Bangladesh', 'India'],
  },
};
